stac-utils/rustac

Cargo.toml, src/catalog.rs, src/collection.rs, src/error.rs, src/fs.rs, src/item.rs, src/lib.rs, src/link.rs, src/object.rs, src/utils.rs
A catchall enum that can be any of the STAC object types.
=> Add stac::Object

src/catalog.rs, src/collection.rs, src/item.rs, src/lib.rs
Add some more links and other useful text.
=> docs: documentation fixups

.github/workflows/rust.yml, Cargo.toml, src/href.rs, src/reader.rs, src/stac.rs
- Use caching
- Run on macos and windows as well
=> CI updates

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml, README.md, RELEASING.md
A quick second release to update crates.io with good readme, etc.
=> Release v0.0.2

src/href.rs
- #33 
Adds `Href::rebase` to set a new "root" for a `Href`.
=> feat: add Href::rebase

ARCHITECTURE.md, CHANGELOG.md, README.md
Adds an architecture diagram using mermaid.
=> Add an architecture diagram

.github/actions-rs/grcov.yml, .github/workflows/ci.yml, CHANGELOG.md, README.md
Adds coverage (and coveralls) to CI
=> Add coverage

.github/workflows/ci.yml
=> Switch to codecov

CHANGELOG.md, src/layout.rs, src/lib.rs, src/stac.rs, src/stac/mod.rs, src/stac/walk.rs
Refactor `Walk`, and make a lot of documentation fixes.
=> Walk refactor

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml, src/href.rs, src/object.rs
A couple of miscellaneous fixes.
=> Misc fixes

CHANGELOG.md, src/link.rs
=> Add links iterators

CHANGELOG.md, src/catalog.rs, src/collection.rs, src/item.rs, src/link.rs, src/value.rs
=> Set root and self links

CHANGELOG.md, src/link.rs
=> Add self link generator

CHANGELOG.md, src/extensions.rs, src/validate.rs
=> Simplify validation

CHANGELOG.md, examples/item-collection.json, src/io.rs, src/item.rs, src/lib.rs, src/validate.rs, src/value.rs
=> Add item collection

CHANGELOG.md, src/value.rs
This is mostly for display purposes.
=> Add Value::type_name

CHANGELOG.md, Cargo.toml, README.md
=> Release v0.2.0

CHANGELOG.md, stac/src/link.rs
=> Add geojson method to link

CHANGELOG.md, stac/src/link.rs
=> Add is_json and is_geojson to Link

CHANGELOG.md, stac/src/link.rs
=> Add Link::set_query_pair

stac-api/CHANGELOG.md, stac-api/src/collections.rs
=> Create stac_api collections from a vec

README.md, stac-api/README.md, stac-async/README.md, stac/README.md
=> Update the readmes

stac-api/CHANGELOG.md, stac-api/examples/planetary-computer-page.geojson, stac-api/src/builder.rs, stac-api/src/fields.rs, stac-api/src/item_collection.rs, stac-api/src/lib.rs, stac-api/src/search.rs, stac-api/src/sort.rs, stac-async/CHANGELOG.md, stac-async/Cargo.toml, stac-async/src/api_client.rs, stac-async/src/client.rs, stac-async/src/error.rs, stac-async/src/io.rs, stac-async/src/lib.rs, stac/CHANGELOG.md, stac/src/value.rs
Rudimentary, post-only search is supported -- good exercise in working with streams.
=> Add an API client

stac-async/src/api_client.rs
=> Fix paging when it's the last page

stac-api/src/builder.rs, stac-api/src/lib.rs, stac-async/Cargo.toml, stac-async/src/api_client.rs, stac-async/src/client.rs, stac-async/src/error.rs, stac-async/src/lib.rs
=> Add more denies

README.md, RELEASING.md
=> Update README and RELEASING

stac/CHANGELOG.md, stac/src/catalog.rs, stac/src/collection.rs, stac/src/item.rs
- Closes #148 
- Wanted by https://github.com/gadomski/stac-server-rs/pull/2
=> Add TryFrom<Map> for all three object types

stac/CHANGELOG.md, stac/src/item_collection.rs
=> impl `FromIterator` for `ItemCollection`

stac-async/CHANGELOG.md, stac-async/src/download.rs, stac-async/src/error.rs, stac-async/src/lib.rs, stac-cli/CHANGELOG.md, stac-cli/src/download.rs, stac-cli/src/error.rs
- Closes #143 
Its not super polished, but it's a good foundation to improve later I think.
=> Add progress reporting to downloads

stac-cli/CHANGELOG.md, stac-cli/src/args.rs, stac-cli/src/error.rs
=> Add validation to cli

stac-api/CHANGELOG.md, stac-api/Cargo.toml, stac-api/README.md, stac-async/Cargo.toml
=> Release stac-api v0.2.0

.github/workflows/release.yml
- Closes #154 
I'm not quite grokking cross compliation, so just using the Github runner(s) for now.
=> Add a simple release workflow

stac-cli/CHANGELOG.md, stac-cli/Cargo.toml
_Hopefully_ we can get binaries on this release.
=> Release stac-cli v0.0.3

stac-api/Cargo.toml, stac-async/Cargo.toml, stac-async/README.md, stac-cli/Cargo.toml, stac-validate/Cargo.toml, stac-validate/README.md, stac/CHANGELOG.md, stac/Cargo.toml, stac/README.md
=> Release stac v0.5.0

stac-validate/CHANGELOG.md, stac-validate/Cargo.toml
=> Release stac-validate v0.1.0

stac-async/src/api_client.rs
=> Fix items docs for async

stac-api/CHANGELOG.md, stac-api/README.md, stac-api/src/error.rs, stac-api/src/fields.rs, stac-api/src/filter.rs, stac-api/src/items.rs, stac-async/src/api_client.rs
We'll need to dry this up for search but it's a good start.
=> Better conversion methods for items

stac/CHANGELOG.md, stac/README.md, stac/src/error.rs, stac/src/item.rs
=> Add bbox and datetime intersections

stac/CHANGELOG.md, stac/src/datetime.rs, stac/src/geo.rs, stac/src/item.rs, stac/src/lib.rs
=> Add geo and datetime mods

stac-api/CHANGELOG.md, stac-api/src/item_collection.rs
=> Impl default for api item_collection

stac-api/CHANGELOG.md, stac-api/Cargo.toml, stac-api/README.md, stac-async/Cargo.toml
Whoops, should have been a v0.3.0 instead of v0.2.1. Yanked v0.2.1.
=> Release stac-api v0.3.0

stac-cli/CHANGELOG.md, stac-cli/README.md, stac-cli/src/args.rs, stac-cli/src/command.rs, stac-cli/src/lib.rs, stac/src/catalog.rs, stac/src/collection.rs, stac/src/item.rs
=> Add sort to CLI

stac-api/CHANGELOG.md, stac-api/src/collections.rs, stac-api/src/item_collection.rs, stac-api/src/lib.rs, stac-api/src/search.rs
=> Add GetSearch

stac-api/CHANGELOG.md, stac-api/src/error.rs, stac-api/src/search.rs, stac/CHANGELOG.md, stac/src/geometry.rs, stac/src/item.rs, stac/src/lib.rs
Includes a new `Geometry::point` associated function. We should probably add more geometry helpers in the future.
=> Validate search

stac/src/error.rs, stac/src/link.rs
set-query is gone but we left some cruft.
=> Remove unused code

stac/src/link.rs
=> Add make_absolute_links_relative

stac-async/Cargo.toml
=> Update reqwest and http for stac-async

pgstac/src/client.rs, stac-api/CHANGELOG.md, stac-api/src/conformance.rs, stac-api/src/error.rs, stac-api/src/item_collection.rs, stac-api/src/items.rs, stac-api/src/search.rs, stac-async/src/api_client.rs, stac-async/src/client.rs, stac-cli/src/args.rs, stac-cli/src/subcommand.rs
- Supports #244 
Don't repeat all the fields.
=> Refactor stac-api by simplifing structures

stac-api/src/search.rs, stac-cli/src/args.rs, stac-cli/src/subcommand.rs
=> Make GetSearch::ids also comma-deliminted

stac/CHANGELOG.md, stac/src/catalog.rs, stac/src/collection.rs, stac/src/item.rs
=> Remove unnecessary qualifications

stac/CHANGELOG.md, stac/README.md, stac/src/error.rs, stac/src/item.rs
=> impl Try(Into|From)<Feature> for Item

stac/CHANGELOG.md, stac/Cargo.toml, stac/src/error.rs, stac/src/item.rs
=> Use geozero instead of wkb

scripts/requirements.txt
=> Update python deps

stac/CHANGELOG.md, stac/src/bounds.rs
=> Fix bounds to geometry

stac-arrow/Cargo.toml, stac-arrow/src/lib.rs, stac-geoparquet/Cargo.toml
- Enabled by https://github.com/geoarrow/geoarrow-rs/pull/683
=> Update to latest geoarrow

stac-cli/CHANGELOG.md, stac-cli/src/args.rs, stac-cli/src/lib.rs, stac-cli/src/subcommand/migrate.rs, stac-cli/src/subcommand/mod.rs, stac-validate/tests/migrate.rs, stac/CHANGELOG.md, stac/Cargo.toml, stac/examples/bands-v1.0.0.json, stac/examples/bands-v1.1.0-beta.1.json, stac/src/asset.rs, stac/src/band.rs, stac/src/catalog.rs, stac/src/collection.rs, stac/src/data_type.rs, stac/src/error.rs, stac/src/extensions/raster.rs, stac/src/item.rs, stac/src/item_collection.rs, stac/src/lib.rs, stac/src/migrate.rs, stac/src/statistics.rs, stac/src/value.rs, stac/src/version.rs, stac/tests/migrate.rs
- Closes #290 
- Closes #291 (supersedes)
=> Migrate to v1.1.0-beta.1

.github/workflows/ci.yml, pgstac/Cargo.toml, stac-api/CHANGELOG.md, stac-api/Cargo.toml, stac-arrow/Cargo.toml, stac-async/CHANGELOG.md, stac-async/Cargo.toml, stac-cli/CHANGELOG.md, stac-cli/Cargo.toml, stac-cli/src/error.rs, stac-cli/src/format.rs, stac-cli/src/runner.rs, stac-geoparquet/Cargo.toml, stac-server/CHANGELOG.md, stac-server/Cargo.toml, stac-validate/CHANGELOG.md, stac-validate/Cargo.toml, stac-validate/README.md, stac/CHANGELOG.md, stac/Cargo.toml, stac/README.md
=> Release most of the packages

cli/Cargo.toml, core/Cargo.toml, core/src/geoarrow/json.rs, duckdb/Cargo.toml
- https://github.com/geoarrow/geoarrow-rs/pull/760
=> Bump geoarrow to v0.3.0-beta.3

.github/workflows/api.yml, .github/workflows/async.yml, .github/workflows/ci.yml, .github/workflows/cli.yml, .github/workflows/core.yml, .github/workflows/duckdb.yml, .github/workflows/pgstac.yml, .github/workflows/python-cli.yml, .github/workflows/python.yml, .github/workflows/server.yml, .github/workflows/validate.yml, cli/Cargo.toml, server/Cargo.toml, server/src/error.rs
=> Use path filters to limit ci jobs

server/CHANGELOG.md, server/Cargo.toml, server/src/backend/memory.rs, server/src/backend/mod.rs, server/src/backend/pgstac.rs
- Closes #343
Thanks https://users.rust-lang.org/t/async-in-public-trait/108400!
=> Remove async trait

core/Cargo.toml, core/src/gdal.rs
=> Fix bbox when building item

core/CHANGELOG.md, core/data/20201211_223832_CS2.json, core/src/migrate.rs
=> Don't add bands if they're all empty

.github/workflows/api.yml, .github/workflows/async.yml, .github/workflows/cli.yml, .github/workflows/core.yml, .github/workflows/duckdb.yml, .github/workflows/pgstac.yml, .github/workflows/server.yml, .github/workflows/stacrs-cli.yml, .github/workflows/stacrs.yml, .github/workflows/validate.yml
=> Workflow renames

cli/src/args/migrate.rs, cli/src/args/mod.rs, cli/src/input.rs, cli/src/output.rs, core/CHANGELOG.md, core/src/item_collection.rs, core/src/migrate.rs, core/src/value.rs, core/src/version.rs, core/tests/migrate.rs, python/src/lib.rs, validate/src/validator.rs, validate/tests/migrate.rs
=> Read unknown versions

core/CHANGELOG.md, core/src/collection.rs, core/src/item_asset.rs, core/src/lib.rs
Last checkbox for https://github.com/stac-utils/stac-rs/issues/376 until we can release 🎉
=> Add item_assets to Collection

api/Cargo.toml, cli/Cargo.toml, pgstac/Cargo.toml, server/Cargo.toml, validate/Cargo.toml
=> Enable all features on docsrs

docs/cli/index.md, docs/python/api/index.md, docs/python/api/migrate.md, docs/python/api/pystac.md, docs/python/api/read.md, docs/python/api/search.md, docs/python/api/validate.md, docs/python/api/write.md, docs/python/index.md, mkdocs.yml
=> Better social cards

core/CHANGELOG.md, core/Cargo.toml, core/src/lib.rs, core/src/validate/mod.rs, core/src/validate/validator.rs
Hopefully this fixes the CI break in validate.
=> Add reqwest-rustls feature

python/python/stacrs/pystac.py, python/src/write.rs
cc @emmalu thanks for kicking the tyres!
=> Use item collection for write example

cli/src/python.rs
=> Add signal handler to python cli

docs/python/api/index.md, python/README.md
=> Tweak python docs

crates/api/CHANGELOG.md, crates/api/Cargo.toml, crates/api/src/client.rs, crates/api/src/lib.rs
=> Send user-agent

.github/workflows/ci.yml, crates/api/src/error.rs, crates/api/src/search.rs, crates/cli/src/args/items.rs, crates/cli/src/value.rs, crates/core/src/error.rs, crates/core/src/item.rs, python/src/lib.rs, python/src/read.rs, python/src/search.rs
=> Fix clippy lints

crates/core/src/error.rs, crates/core/src/item.rs, crates/core/src/validate/validator.rs
=> Audit errors

crates/cli/src/input.rs, crates/cli/src/subcommand/validate.rs, crates/core/src/error.rs, crates/core/src/lib.rs, crates/core/src/validate/validator.rs
- Closes #485 
- Closes #461 
Also improves the validation error output.
=> Validate collections

.github/pull_request_template.md, .github/workflows/ci.yml, .markdownlint-cli2.jsonc
=> Add markdownlint

crates/api/src/item_collection.rs, crates/core/CHANGELOG.md, crates/core/src/catalog.rs, crates/core/src/collection.rs, crates/core/src/item.rs, crates/core/src/item_collection.rs, crates/core/src/lib.rs, crates/core/src/value.rs, crates/pgstac/src/client.rs
That worked better than expected. The only downside is that the type field is picked up as an extra attribute, but that's not too bad I don't think?
- Closes #394
=> Use internal tagging for Value

crates/core/CHANGELOG.md, crates/core/src/catalog.rs, crates/core/src/collection.rs, crates/core/src/item.rs, crates/core/src/item_collection.rs
=> Permissive deserialization

crates/core/CHANGELOG.md, crates/core/src/validate/validator.rs
=> fix: set user-agent on validator

crates/api/CHANGELOG.md, crates/api/src/search.rs, crates/duckdb/src/lib.rs
=> feat: implement fields for duckdb

.github/workflows/ci.yml, crates/cli/Cargo.toml, crates/cli/src/lib.rs
=> ci: use pre-compiled duckdb

crates/duckdb/src/lib.rs
https://github.com/stac-utils/stac-rs/pull/562#discussion_r1901121226
=> fix: use as binary

crates/core/CHANGELOG.md, crates/core/src/lib.rs
- Closes https://github.com/stac-utils/stac-rs/issues/557
=> feat: re-export geometry

.github/workflows/ci.yml, CONTRIBUTING.md, crates/cli/src/lib.rs, crates/core/src/error.rs, crates/core/src/item.rs, crates/core/src/item_collection.rs, crates/pgstac/src/lib.rs, scripts/format, scripts/lint
=> feat: lint and format scripts

crates/duckdb/src/lib.rs
=> fix(duckdb): use s3 credential chain for duckdb

.github/workflows/python-cli.yml, crates/cli/CHANGELOG.md, crates/cli/Cargo.toml, crates/cli/pyproject.toml, crates/cli/src/lib.rs
Hoping to fix https://github.com/stac-utils/stac-rs/issues/630
=> feat: update cli wheels, always bundle duckdb

crates/cli/src/lib.rs
=> feat: serve items without a collection

crates/core/Cargo.toml, crates/core/src/format.rs, crates/core/tests/aws.rs, crates/core/tests/examples.rs
- Closes https://github.com/stac-utils/stac-rs/issues/414
=> feat: get aws creds from env

.github/workflows/ci.yml, crates/cli/README.md, crates/duckdb/README.md
=> docs: add some notes about duckdb bundling

.github/workflows/duckdb.yml
=> feat: add duckdb bundled workflow

.github/workflows/labels.yml, Cargo.toml
Want to pick up https://github.com/duckdb/duckdb-rs/pull/437
=> deps: patch duckdb

Cargo.toml
=> deps: bump arrow

crates/cli/src/lib.rs, crates/core/CHANGELOG.md, crates/core/src/format.rs
https://github.com/stac-utils/stacrs/issues/76
=> fix: default to snappy compression

Cargo.toml, crates/api/Cargo.toml, crates/api/src/items.rs, crates/core/Cargo.toml, crates/core/src/asset.rs, crates/core/src/collection.rs, crates/core/src/item.rs, crates/extensions/Cargo.toml, crates/extensions/src/authentication.rs
Will solve https://github.com/stac-utils/rustac-py/issues/85 once this propogates to **rustac-py**.
=> fix: use indexmap, not hashmap

.github/workflows/cd.yml, .github/workflows/ci.yml, Cargo.toml, crates/core/Cargo.toml, crates/core/src/error.rs, crates/core/src/geoarrow/json.rs, crates/core/src/geoarrow/mod.rs, crates/core/src/geoparquet/feature.rs, crates/duckdb/Cargo.toml, crates/duckdb/src/lib.rs
- geoarrow-rs no longer has `Table` or `ChunkedArray` concepts. This is for symmetry with upstream `arrow`, to nudge people to use iterators (especially `RecordBatchReader`) as much as possible, simplicity and maintenance, and because I think higher-level libraries like DataFusion will take care of the "table" case. I think for now, if you need a "table" construct, it's best to have a struct wrapping `(Vec<RecordBatch>, Arc<Schema>)` yourself. 
- 
- List any issues that this pull request closes
- Delete this section if it is not applicable
- List any issues that this pull request is related to
- Delete this section if it is not applicable
Description of the changes, including any "sidecar" changes that came along (e.g. small bugfixes you found along the way).
Delete any checklist items …
=> deps: update geoarrow-rs

crates/duckdb/src/client.rs
@bitner think this is worth adding to **cql2-rs**? Motivation: I need to pre-check the properties against the geoparquet schema to just return nothing for the search instead of erroring.
=> feat: check column names in duckdb filter

README.md, docs/index.md
Updated the logo attribution ... I snipped the prompt a bit, but I think it captures the core concept?
=> docs: update attribution for logo

crates/core/data/multi-polygons.json, crates/core/src/geoarrow/mod.rs, crates/core/src/geoparquet/feature.rs
- Closes #722 
- Closes #680 as OBE
=> fix: proj:geometry

.github/workflows/ci.yml, crates/core/CHANGELOG.md, crates/core/src/format.rs
Closes #643 
I'm still not convinced by my decision to use `Format` as the base for all this IO, but at least it makes clear what format you're expecting to be reading/writing stuff in so 🤷🏼? No immediate plans to refactor ...
In support of https://github.com/stac-utils/rustac-py/issues/117
=> feat: provide API for using your own object store

Cargo.toml, crates/wasm/Cargo.toml, crates/wasm/LICENSE-APACHE, crates/wasm/LICENSE-MIT, crates/wasm/README.md, crates/wasm/src/lib.rs, crates/wasm/www/.gitignore, crates/wasm/www/bootstrap.js, crates/wasm/www/index.html, crates/wasm/www/index.js, crates/wasm/www/package-lock.json, crates/wasm/www/package.json, crates/wasm/www/webpack.config.js
- #218 
It's by no means complete, but it's a start. We'll want to add CI and such later.
=> feat: wasm

Cargo.toml, crates/cli/CHANGELOG.md, crates/cli/Cargo.toml, crates/cli/src/lib.rs, crates/core/CHANGELOG.md, crates/io/src/format.rs, crates/io/src/store.rs
=> feat: crawl

crates/duckdb/CHANGELOG.md, crates/duckdb/src/client.rs
=> feat: add union by name to duckdb
