- src/catalog.rs
- src/collection.rs
- src/core.rs
- src/item.rs
- src/lib.rs
- src/object.rs
- src/reader.rs
This improves our ergonomics by allowing access to common fields from either the main object types e.g. `Catalog` or from the enum wrapper `Object`. Also will let us guard certain fields, e.g. `links`, when we're working with trees.
> Use a common base object and trait

- Cargo.toml
- src/error.rs
- src/href.rs
- src/lib.rs
- src/reader.rs
- src/stac.rs
Store `String` instead of `PathBuf` since we want to default to '/'-delimited cheaply.
> Change href interface

- CHANGELOG.md
- README.md
- examples/copy.rs
- src/lib.rs
- src/render.rs
Fixes the type signature for `BestPracticesRender`, because it was making us return an `Error` unnecessarily.
Sidecar:
- Test README.md doctests
- Small wording change in lib documentation
> Fix renderer type signature

- CHANGELOG.md
- src/render.rs
Simplifies how `Render` creates hrefs.
> Simplify render href

- CHANGELOG.md
Small fix to changelog formatting.
> Small formatting changes to CHANGELOG

- .github/workflows/ci.yml
- .github/workflows/release.yml
- CHANGELOG.md
Breaks off the release action into its own workflow that builds `--release`, tests `--release`, and publishes (dry run). Also improves the cache key to use the `matrix.flags`, and updates changelog for #36 because we forgot.
> Make release its own workflow

- .github/workflows/doc.yml
- CHANGELOG.md
- README.md
- src/href.rs
- src/lib.rs
- src/object.rs
- src/read.rs
- src/stac.rs
- src/write.rs
Refactors the `Stac` API to use a better `Object` and `HrefObject` classes. Also adds strict doc building to CI.
> Refactor `Stac` API

- CHANGELOG.md
- src/stac.rs
> Add `Stac.add_child`

- CHANGELOG.md
- src/error.rs
- src/lib.rs
- src/object.rs
- src/read.rs
- #22: As I'm building a book based on the PySTAC quickstart, I realized that I wanted top-level convenience functions for getting the structures.
Provides top-level convenience functions that allow quickly reading all three object types into their structs.
> Read objects directly

- CHANGELOG.md
- src/error.rs
- src/stac.rs
Cleans up the `Stac` interface and adds more docs and doctests.
> Stac fixup

- .github/workflows/ci.yml
- CHANGELOG.md
- src/href.rs
- src/lib.rs
- src/object.rs
- src/read.rs
- src/stac.rs
- src/write.rs
Add crate-specific `Result` type.
> Add crate-specific `Result`

- src/href.rs
- src/layout.rs
- src/lib.rs
- src/stac.rs
- Closes #52 
- Closes #33 
Adds the `NextHref` trait and the `Rebase` and `BestPractices` implementors.
> Add NextHref trait and Rebase

- CHANGELOG.md
- benches/layout.rs
- examples/copy.rs
- src/layout.rs
- src/lib.rs
- src/stac.rs
Removes `next_href` by doing more work on the children while laying out. Requires layout to become mutable while laying out.
> fix: remove next_href

- .github/workflows/ci.yml
- Closes #69 
- Unblocks #68 
- Unblocks #66 
Set the "fail if coverage is bad" flag to false.
> Don't fail ci if cov error

- README.md
Adds a note to the readme re: the incubator repo.
> Reference the incubator repo in readme

- CHANGELOG.md
- codecov.yml
- src/asset.rs
- Closes #65 
Renames `type_` to `type` on asset to bring it into alignment with the rest of the structures.
> Rename type_ to r#type on asset

- CHANGELOG.md
- src/read.rs
`Read::read_json` was taking a generic `Into<PathBufHref>`, which was causing us to clone the href in the default read. By just taking a `&PathBufHref` instead, we eliminate the clone.
`read_json` is a relatively low-level function so I'm ok w/ it not being generic -- having to create the href yourself beforhand feels ok.
> `read_json` takes a ref

- CHANGELOG.md
- Cargo.toml
- README.md
- src/lib.rs
- src/read.rs
- Closes #67
Make reqwests optional. We should nudge folks to use the (as of yet uncompleted) `stac-async` library to do actual, good IO.
> Make reqwest optional

- CHANGELOG.md
- src/href.rs
- src/lib.rs
- src/read.rs
- src/stac/mod.rs
- src/write.rs
- Closes #75 
Remove `PathBufHref` and impl `FromStr` for `Href`. It was too complex for what it needed to be. The `Href::to_slash` method is the new cross-platform href entrypoint.
> Remove PathBufHref

- CHANGELOG.md
- codecov.yml
- src/object.rs
Add assets accessor for object.
> Add assets accessor for object

- CHANGELOG.md
- Cargo.toml
- README.md
- RELEASING.md
v0.0.5
```text
Added:
- `Href` trait
- `Value`
Changed:
- `Asset.type_` is now `Asset.r#type`
- `reqwest` is now an optional feature
Removed:
- `PathBufHref`
- `Href::into_string`
- `Stac`
- `Layout`
- `Reader`
- `Writer`
- `Object`
- `Href` struct
- benchmarks
```
> Release v0.0.5

- CHANGELOG.md
- src/io.rs
- src/lib.rs
Also removes read_from_url and read_from_path from public API.
> Add read_json

- CHANGELOG.md
- Cargo.toml
- README.md
0.1.0
```text
Added:
- `stac::read_json`
Changed:
- Module layout
Removed:
- `Item::set_collection` and `Item::collection_link`
- CI coverage
- `stac::read_from_url` and `stac::read_from_path`
Fixed:
- Documentation examples
```
> Release v0.1.0

- CHANGELOG.md
- src/error.rs
Use Error::IncorrectType instead
> Deprecate Error::TypeMismatch

- CHANGELOG.md
- src/catalog.rs
- src/collection.rs
- src/item.rs
- src/lib.rs
- src/link.rs
- src/value.rs
Add a links trait that can be used for quick access to links of various rel types.
> Add links trait

- CHANGELOG.md
- Cargo.toml
0.1.2
I'd like to get the links updates out before the next breaking change.
- Needs to go in before #102
> Release v0.1.2

- CHANGELOG.md
- src/catalog.rs
- src/collection.rs
- src/lib.rs
- src/value.rs
- Closes #98 
Because valid collections and catalogs need a non-empty description field, it makes sense to require description for the initializer.
BREAKING CHANGE: changes the signature of the `new` methods
> Add description

- CHANGELOG.md
- src/collection.rs
> Set the default license for collections

- CHANGELOG.md
- src/error.rs
- src/link.rs
A little untested on the local paths side but it's cribbed from tested code so shrug.
> Make relative hrefs absolute

- CHANGELOG.md
- src/error.rs
> Remove deprecated error type

- CHANGELOG.md
- stac/src/item.rs
- n/a
- n/a
ItemCollection `links` was not pub, so a user outside this module cannot access it. A specific use case this prevents is retreiving search results from a STAC API and then using the `next` link to get the next page of results.
> make ItemCollection 'links' field public

- .github/workflows/ci.yml
- CHANGELOG.md
- stac/src/link.rs
This lets use remove the Href constraints for links, since not everything that has links needs to have an href.
> `make_relative_links_absolute` now takes an href

- CHANGELOG.md
- stac/src/item.rs
I have a feeling we'll accumulate these builder-pattern setters all over the place as we find them useful. Not the worst thing, but I just don't want to make them all right now.
> Add Item::collection setter

- Cargo.toml
- README.md
- stac-api/CHANGELOG.md
- stac-api/Cargo.toml
- stac-api/src/collections.rs
- stac-api/src/error.rs
- stac-api/src/fields.rs
- stac-api/src/item_collection.rs
- stac-api/src/lib.rs
- stac-api/src/link.rs
- stac-api/src/link_builder.rs
- stac-api/src/root.rs
- stac-api/src/search.rs
- stac-api/src/sort.rs
I was building the API crate over at [stac-server-rs](https://github.com/gadomski/stac-server-rs/blob/bc98dc916059ceb9e0bfd0f4241ec0b9586815e2/stac-api/src/lib.rs), but it was getting interesting enough for inclusion in the core repo, I think. Plus, now these data structures are reusable by other libraries -- e.g. I think I can use the search stuff in [pgstac-rs](https://github.com/gadomski/pgstac-rs/).
Once this PR merges, I'll release it as v0.1.0.
cc @philvarner b/c I know you were working w/ API-based data structures for [stac-siphon-rs](https://github.com/philvarner/stac-siphon-rs).
> Add stac-api crate

- stac/CHANGELOG.md
- stac/Cargo.toml
- stac/README.md
- stac/src/error.rs
- stac/src/link.rs
- Replaces #121 
Adds `Link::set_query` behind a `set_query` feature.
> Adds Link::set_query

- stac-api/CHANGELOG.md
- stac-api/src/builder.rs
- stac-api/src/lib.rs
Breaks out the url construction to its own builder, which will be used (e.g.) for an async API client.
> feat: add url builder

- stac-async/CHANGELOG.md
- stac-async/src/io.rs
- stac-async/src/lib.rs
- stac/CHANGELOG.md
- stac/README.md
- stac/examples/validate.rs
- stac/src/href.rs
- stac/src/io.rs
- stac/src/item.rs
- stac/src/lib.rs
- stac/src/link.rs
- stac/src/validate.rs
- stac/src/value.rs
Previously, we had a `from_json` method -- this PR moves that logic down into deserialize itself, making our read interfaces a bit cleaner. This is breaking, since previously we always returned a `Value` -- now we can go straight to an `Item` from `stac::read`, if we want.
We couldn't use tagged enums b/c the tag deserialization strips the field, and we need it on the underlying data structure.
We also implemented the same interface for **stac-async**.
> Implement `Deserialize` for `Value`

- stac/CHANGELOG.md
- stac/src/catalog.rs
- stac/src/collection.rs
- stac/src/item.rs
- stac/src/item_collection.rs
- stac/src/lib.rs
- stac/src/value.rs
- Improves on serialization changes in #135 
After thinking about it, I realized I could push the serialize/deserialize checks to the items themselves, and then just use untagged for `Value`. Much nicer.
Includes some movement of where stuff is defined, and removes some now-useless conversion methods. Probably breaking, but we're already committed to a major so not stressing about it.
> Deserialize with

- stac/CHANGELOG.md
- stac/src/asset.rs
- stac/src/catalog.rs
- stac/src/collection.rs
- stac/src/extensions.rs
- stac/src/item.rs
- stac/src/lib.rs
- I'll use this for #134, because I'll want to generalize the behavior over anything that has assets
Adds an assets trait. Also changes `Collection::assets` to non-optional (breaking api change but we're committed).
> Add assets trait

- release.toml
- stac/CHANGELOG.md
- stac/Cargo.toml
Last release of the v0.3 line before the breaking changes from #135.
https://crates.io/crates/stac/0.3.2
> Release v0.3.2

- stac/CHANGELOG.md
- stac/src/catalog.rs
- stac/src/collection.rs
- stac/src/item.rs
- stac/src/item_collection.rs
These shouldn't be directly set by a downstream user. We're taking advantage of the fact that we've already broken backwards compatibility in **main** to make this change.
> Make the type and version fields private

- Cargo.toml
- README.md
- stac-async/CHANGELOG.md
- stac-async/Cargo.toml
- stac-async/src/download.rs
- stac-async/src/error.rs
- stac-async/src/io.rs
- stac-async/src/lib.rs
- stac-cli/CHANGELOG.md
- stac-cli/Cargo.toml
- stac-cli/README.md
- stac-cli/src/args.rs
- stac-cli/src/download.rs
- stac-cli/src/error.rs
- stac-cli/src/lib.rs
- stac-cli/src/main.rs
- stac/CHANGELOG.md
- stac/src/href.rs
- stac/src/io.rs
- stac/src/lib.rs
- stac/src/link.rs
- Closes #134 
After we merge this, we can archive https://github.com/gadomski/stac-incubator-rs -- its watch has ended.
Brought over the cli to exercise the downloader. We'll need to add progress reporting back in, but I'll track that in a new issue.
> Add downloader

- stac-async/src/download.rs
- stac-async/src/error.rs
- stac-cli/src/args.rs
- stac-cli/src/error.rs
> Remove unimplemented

- RELEASING.md
- stac-api/Cargo.toml
- stac-async/Cargo.toml
- stac-cli/Cargo.toml
- stac/CHANGELOG.md
- stac/Cargo.toml
- stac/README.md
Also, update the releasing docs.
> Release stac v0.4.0

- stac-async/CHANGELOG.md
- stac-async/Cargo.toml
- stac-async/README.md
- stac-cli/Cargo.toml
We might have gotten away with a minor release, but it's hard to tell b/c of the refactor so better safe then sorry.
> Release stac-async v0.4.0

- stac-async/src/api_client.rs
- stac-async/src/download.rs
- stac-async/src/lib.rs
> Add stac-async docs

- stac/CHANGELOG.md
- stac/Cargo.toml
- stac/src/link.rs
Not used anymore. Breaking on **stac**.
> Remove set query pairs

- stac/CHANGELOG.md
- stac/src/link.rs
> Make `Links.remove_*` the same-ish

- stac-validate/Cargo.toml
- stac-validate/src/lib.rs
- stac/CHANGELOG.md
- stac/Cargo.toml
- stac/README.md
- stac/src/item.rs
- stac/src/lib.rs
> Use our own Geometry struct

- stac-api/CHANGELOG.md
- stac-api/Cargo.toml
- stac-api/README.md
- stac-api/src/collections.rs
- stac-api/src/conformance.rs
- stac-api/src/fields.rs
- stac-api/src/filter.rs
- stac-api/src/item_collection.rs
- stac-api/src/items.rs
- stac-api/src/root.rs
- stac-api/src/search.rs
- stac-api/src/sort.rs
- stac/CHANGELOG.md
- stac/Cargo.toml
- stac/README.md
- stac/src/asset.rs
- stac/src/catalog.rs
- stac/src/collection.rs
- stac/src/item.rs
- stac/src/link.rs
Will (hopefully) enable OpenAPI documentation for **stac-server-rs**.
Needs geojson schemars support, or we need to implement or own geometry class. Neither option is awesome.
> Add schemars support

- stac/CHANGELOG.md
- stac/src/lib.rs
We want to use it in *pgstac-rs*.
> Make (de)serialize_type public

- stac-cli/CHANGELOG.md
- stac-cli/Cargo.toml
- stac-cli/src/args.rs
- stac-cli/tests/data/collection-bad-temporal.json
- stac-validate/CHANGELOG.md
- stac-validate/src/validate.rs
- Closes #185 
Implements `Validate` for `serde_json::Value`, then only parse the JSON before starting validation.
New error message:
```shell
$ stac validate stac-cli/tests/data/collection-bad-temporal.json
Validation error at /extent/temporal: [["2020-12-11T22:38:32.125Z","2020-12-14T18:02:31.437Z"]] is not of type "object"
ERROR: validation errors
```
> Better validation error messages

- stac-api/CHANGELOG.md
- stac-api/src/conformance.rs
- stac-api/src/lib.rs
> Add ITEM_SEARCH_URI

- README.md
- stac-cli/CHANGELOG.md
- stac-cli/Cargo.toml
- stac-cli/README.md
- stac-cli/src/command.rs
- stac-cli/src/commands/mod.rs
- stac-cli/src/commands/search.rs
- stac-cli/src/commands/sort.rs
- stac-cli/src/commands/validate.rs
- stac-cli/src/error.rs
- stac-cli/src/lib.rs
- Closes #147 
That was ... easier than expected. I'm sure there's some cleanup work to do around the clap arguments, since I just copied them straight from `GetSearch`, but we'll touch those up as we use them and break them.
> Add search to CLI

- stac/CHANGELOG.md
- stac/src/item.rs
> Add Item.intersects

- stac/CHANGELOG.md
- stac/src/asset.rs
- stac/src/item.rs
- Closes #196 
I made the editorial decision to exclude some (e.g. license) that really should just be on the collection.
> Add common metadata fields

- RELEASING.md
- stac/CHANGELOG.md
- stac/src/item.rs
- I removed it in https://github.com/stac-utils/stac-rs/pull/202 but that was too aggressive.
> Deprecate, don't remove, intersects_bbox

- stac-cli/CHANGELOG.md
- stac-cli/src/command.rs
- stac-cli/src/commands/validate.rs
- stac-cli/src/error.rs
> Validate collections endpoint

- stac-async/CHANGELOG.md
- stac-async/src/api_client.rs
- Closes #219
Adds a `with_client` method to allow setting up an `ApiClient` with custom behavior.
> Add `ApiClient::with_client`

- stac-cli/CHANGELOG.md
- stac-cli/Cargo.toml
- stac-cli/data
- stac-cli/src/command.rs
- stac-cli/src/commands/validate.rs
- stac-cli/tests/command.rs
- Closes #231 
Includes some tests for the CLI.
> Allow stdin for validate

- stac-cli/CHANGELOG.md
- stac/CHANGELOG.md
- stac/src/extensions/projection.rs
- stac/src/gdal.rs
- Closes #239
_Technically_ a breaking change to the `Projection::shape` type, but we're going to just skate past it b/c its new (I'll pretend it a bugfix).
> Add more proj fields to gdal item creation

- stac-cli/CHANGELOG.md
- stac-cli/src/command.rs
- stac-cli/src/commands/sort.rs
- stac-cli/tests/command.rs
> Allow stdin for stac-cli sort

- .github/workflows/ci.yml
- stac/CHANGELOG.md
- stac/Cargo.toml
- stac/README.md
- stac/src/error.rs
- stac/src/item.rs
- Helps #256
Going to and from **stac-geoparquet** structure requires a little logic, none of which actually depends on **geoparquet** or **geoarrow**, just **wkb**. This PR adds those conversions with a new `wkb` feature.
> Add wkb feature and GeoparquetItem

- stac/src/item.rs
Just the conversion methods do.
> GeoparquetItem doesn't need wkb feature

- stac/CHANGELOG.md
- stac/examples/auth/collection.json
- stac/examples/auth/item.json
- stac/src/extensions/authentication.rs
- stac/src/extensions/mod.rs
> Add authentication extension

- stac/CHANGELOG.md
- stac/examples/eo/item.json
- stac/src/extensions/electro_optical.rs
- stac/src/extensions/mod.rs
> Add eo extension

- .github/workflows/ci.yml
- stac/CHANGELOG.md
- stac/Cargo.toml
- stac/README.md
- stac/src/error.rs
- stac/src/item.rs
- stac/src/lib.rs
- Discovered while working #256 
Turns out we just want the flat structure, nothing specific to stac-geoparquet.
> Rename GeoparquetItem to FlatItem

- stac/CHANGELOG.md
- stac/src/extensions/projection.rs
We got bit by https://gdal.org/tutorials/osr_api_tut.html#crs-and-axis-order
> Fix axis mapping strategy for gdal wgs84 bounds/geom

- stac/Cargo.toml
- stac/src/extensions/projection.rs
- stac/src/gdal.rs
- Closes (supersedes) #282 and #283 
Also remove the bindgen, since newer gdal crates have moar bindings. We could maybe do to add some doc notes about building with `-F gdal/bindgen` if out-of-the-box building doesn't work, but it's only speculative at this point.
> Bump gdal crates

- spec-examples/v1.1.0-beta.1/README.md
- spec-examples/v1.1.0-beta.1/catalog.json
- spec-examples/v1.1.0-beta.1/collection-only/collection-with-schemas.json
- spec-examples/v1.1.0-beta.1/collection-only/collection.json
- spec-examples/v1.1.0-beta.1/collection.json
- spec-examples/v1.1.0-beta.1/collectionless-item.json
- spec-examples/v1.1.0-beta.1/core-item.json
- spec-examples/v1.1.0-beta.1/extended-item.json
- spec-examples/v1.1.0-beta.1/extensions-collection/collection.json
- spec-examples/v1.1.0-beta.1/extensions-collection/proj-example/proj-example.json
- spec-examples/v1.1.0-beta.1/simple-item.json
- stac-validate/CHANGELOG.md
- stac-validate/Cargo.toml
- stac-validate/src/error.rs
- stac-validate/src/lib.rs
- stac-validate/src/validate.rs
- stac-validate/src/validator.rs
- stac-validate/tests/examples.rs
- stac/CHANGELOG.md
- stac/src/catalog.rs
- stac/src/collection.rs
- stac/src/error.rs
- stac/src/item.rs
- stac/src/lib.rs
- stac/src/version.rs
- Helps #290
- This PR is the first of a couple that will break #291 into more digestible chunks
- Switches to using a `Version` enum (breaking change to **stac**)
- Adds support for validating new versions to **stac-validate** (breaking changes to **stac-validate**)
- Validates all v1.1.0-beta.1 examples
> Begin support for v1.1.0-beta.1

- pgstac/src/client.rs
- stac-api/src/items.rs
- stac/CHANGELOG.md
- stac/Cargo.toml
- stac/examples/bands-v1.1.0-beta.1.json
- stac/src/item.rs
- stac/src/lib.rs
> Use `DateTime<Utc>` instead of `String` for datetimes

- stac/CHANGELOG.md
- stac/src/io.rs
- stac/src/item.rs
- stac/src/lib.rs
- stac/src/migrate.rs
It doesn't really belong in our lib's API.
> Make `io::read_json` pub(crate)

- scripts/requirements-stac-geoparquet.txt
- stac-arrow/examples/two-sentinel-2-items.json
- stac-arrow/src/json.rs
- stac-arrow/src/lib.rs
- This issue describes what's going on: https://github.com/stac-utils/stac-geoparquet/issues/77
> Don't include null assets when deseiralizing from arrow

- .github/workflows/core.yml
- cli/Cargo.toml
- cli/src/args/items.rs
- cli/src/args/mod.rs
- cli/src/args/serve.rs
- cli/src/error.rs
- cli/src/input.rs
- cli/src/lib.rs
- cli/src/options.rs
- cli/src/output.rs
- cli/src/value.rs
- core/Cargo.toml
- core/README.md
- core/src/error.rs
- core/src/format.rs
- core/src/io.rs
- core/src/item_collection.rs
- core/src/lib.rs
- core/src/object_store.rs
Tested s3 and it worked!
```shell
$ cargo run -- -c aws_access_key_id='<redacted>' -c aws_secret_access_key='<redacted>' -c aws_region=us-east-2 translate -vvv https://raw.githubusercontent.com/radiantearth/stac-spec/master/examples/simple-item.json s3://gadomski/simple-item.json
2024-09-12T23:22:12.739240Z  INFO object_store::aws::builder: Using Static credential provider
2024-09-12T23:22:12.747527Z DEBUG reqwest::connect: starting new connection: https://raw.githubusercontent.com/    
2024-09-12T23:22:12.747788Z DEBUG hyper_util::client::legacy::connect::dns: resolving host="raw.githubusercontent.com"
2024-09-12T23:22:12.752389Z DEBUG hyper_util::client::legacy::connect::http: connecting to 185.199.108.133:443
2024-09-12T23:22:12.757321Z DEBUG hyper_util::client::legacy::connect::http: …
```
> Move i/o to core

- duckdb/Cargo.toml
- More information on geoparquet support here: https://github.com/duckdb/duckdb_spatial/issues/27
v1.1, though it supposedly has geoparquet support, breaks things. Pin this for now.
> Pin to v1.0

- cli/src/args/validate.rs
- core/CHANGELOG.md
- core/src/lib.rs
- python/Cargo.toml
- python/src/validate.rs
- server/src/api.rs
- validate/CHANGELOG.md
- validate/Cargo.toml
- validate/README.md
- validate/src/blocking.rs
- validate/src/error.rs
- validate/src/lib.rs
- validate/src/validate.rs
- validate/src/validator.rs
- validate/tests/examples.rs
- validate/tests/migrate.rs
- Closes #207
This popped up as a need while working on #376 — when I updated the default version to v1.1.0, some server tests broke because they were validating within a tokio runtime.
> Async validation

- core/CHANGELOG.md
- core/src/asset.rs
- core/src/extensions/authentication.rs
- core/src/extensions/electro_optical.rs
- core/src/extensions/mod.rs
- core/src/extensions/projection.rs
- core/src/extensions/raster.rs
- core/src/fields.rs
- core/src/gdal.rs
- Closes #401 
- Closes #272 as OBE
Inheritance wasn't ever going to work, was it?
> Remove extensions vec from asset

- .github/workflows/python.yml
Now that we bundle in duckdb those wheel builds take a hot second.
> Only build python wheels on tag push

- crates/api/src/conformance.rs
- crates/api/src/items.rs
- crates/api/src/lib.rs
- crates/cli/Cargo.toml
- crates/cli/src/error.rs
- crates/cli/src/subcommand/search.rs
- crates/cli/src/subcommand/serve.rs
- crates/server/CHANGELOG.md
- crates/server/README.md
- crates/server/src/api.rs
- crates/server/src/backend/memory.rs
- crates/server/src/backend/mod.rs
- crates/server/src/backend/pgstac.rs
- crates/server/src/routes.rs
- scripts/validate-stac-server
> Filter conformance class

- crates/core/CHANGELOG.md
- crates/types/Cargo.toml
- crates/types/src/lib.rs
- crates/types/src/link.rs
-  #501 
Add implementation of `Field` trait for `Link`.
> feat: Add Fields impl for Link

- crates/pgstac/CHANGELOG.md
- crates/pgstac/src/client.rs
- crates/pgstac/src/lib.rs
- crates/server/src/backend/pgstac.rs
This makes it easier to use in upstream Python bindings
> refactor(pgstac): return json, not stac

- crates/api/Cargo.toml
- crates/api/src/lib.rs
- crates/api/src/python.rs
- crates/pgstac/CHANGELOG.md
This lets both stacrs and pgstacrs use it without pgstacrs having to depend on stacrs.
> feat(api): add python optional feature

- crates/pgstac/CHANGELOG.md
- crates/pgstac/src/lib.rs
Also refactor a bunch of names.
- Supports https://github.com/stac-utils/pgstacrs/issues/7
> feat!(pgstac): add readonly

- Cargo.toml
- crates/pgstac/CHANGELOG.md
- crates/pgstac/Cargo.toml
- crates/pgstac/README.md
- crates/server/CHANGELOG.md
- crates/server/Cargo.toml
No open issue but the change in the PR added to the CHANGELOG should have triggered a release of stac-server. The current release contains the yanked `stac-types` crate which is breaking our build.
No code changes, just a note to trigger a release
> release(stac-server): remove stac-types dependency

- README.md
- crates/cli/README.md
- crates/cli/data/invalid-item.json
- crates/cli/src/lib.rs
- crates/core/CHANGELOG.md
- crates/core/src/error.rs
- crates/core/src/lib.rs
> feat: validate in cli

- crates/core/src/format.rs
- crates/core/tests/examples.rs
small change to add object-store-aws test, also add example on how to use keys.
> add object-store-aws test

- crates/cli/CHANGELOG.md
- crates/cli/Cargo.toml
- crates/cli/src/lib.rs
We force the logging in the lib...this _could_ cause problems down the road if we want the **stacrs** wrapper to use this, but also log, but then we could provide an option then to not do the setup. For now, this fixes things.
> release: stac-cli v0.5.3

- crates/duckdb/src/lib.rs
I _think_ we'll want to set the `geoarrow.wkb` field extension as shown here so we can later load our produced record batches into GeoPandas, etc. GeoPandas doesn't understand `geoarrow.geometry` yet, which is what our wkb-parsing workflow produces.
Not sending b/c I can't test w/ GeoPandas downstream in **stacrs** yet because <gestures in Rust+Python> that I haven't been able to unpick yet.
> feat(duckdb): set wkb metadata

- .github/workflows/ci.yml
- crates/cli/CHANGELOG.md
- crates/cli/Cargo.toml
- crates/cli/src/lib.rs
- crates/server/CHANGELOG.md
- crates/server/Cargo.toml
- crates/server/data/100-sentinel-2-items.parquet
- crates/server/src/backend/duckdb.rs
- crates/server/src/backend/mod.rs
- crates/server/src/error.rs
- crates/server/src/lib.rs
Doesn't quite close https://github.com/stac-utils/stac-rs/issues/644 b/c here we're just referencing an existing **stac-geoparquet** file ... going to an in-memory DuckDB database is a different thing.
> feat: duckdb server backend

- crates/duckdb/CHANGELOG.md
- crates/duckdb/src/lib.rs
> feat: return duckdb extensions

- crates/cli/src/lib.rs
- crates/cli/src/main.rs
This lets us _not_ do it over in Python, and instead set up our own logging.
> feat(cli): optionally disable tracing subscriber init

- Cargo.toml
- crates/core/src/geoarrow/mod.rs
- crates/core/src/geoparquet/feature.rs
> feat: stac-geoparquet version in metadata

- Cargo.toml
- crates/cli/src/lib.rs
- crates/duckdb/CHANGELOG.md
- crates/duckdb/src/lib.rs
> feat: more logging, default to false

- crates/core/CHANGELOG.md
- crates/core/src/geoarrow/json.rs
- crates/core/src/geoparquet/feature.rs
I think we get a performance win, because we one-pass the conversion. Turns out this code needed a refactor, thanks @ceholden for poking it.
ref https://github.com/stac-utils/rustac-py/issues/124
> fix: read geometries better

- crates/core/CHANGELOG.md
- crates/core/src/geoarrow/mod.rs
- crates/core/src/item.rs
Though the spec [recommends dropping it](https://github.com/stac-utils/stac-geoparquet/blob/a59ba7638117fc12c12784dbbe7dbd8c2d583b88/spec/stac-geoparquet-spec.md?plain=1#L23), I'd like to keep it for now:
- There's already at least one other probably-identical string field in the file (`stac_version`) so if we're trying to optimize on size we could play with metadata more to cut more columns
- Naïve geoparquet readers are more likely to be able to reconstruct valid STAC items if all the required fields are present ... without `type`, you really have to know what you're doing
- In our case, when we search **stac-geoparquet** we don't assume that we're returning valid STAC items, because the `fields` extension can be used to strip away required fields. Because of that, a direct conversion …
> fix: keep type on flat item

- Cargo.toml
- crates/core/Cargo.toml
- crates/core/src/error.rs
- crates/core/src/geoarrow/json.rs
- crates/core/src/geoarrow/mod.rs
- crates/core/src/geoparquet.rs
- crates/duckdb/Cargo.toml
- crates/duckdb/src/error.rs
> feat: update geoarrow version, set primary column

- crates/api/src/collections.rs
- crates/api/src/item_collection.rs
- crates/cli/src/lib.rs
- crates/core/CHANGELOG.md
- crates/core/src/asset.rs
- crates/core/src/catalog.rs
- crates/core/src/collection.rs
- crates/core/src/href.rs
- crates/core/src/item.rs
- crates/core/src/item_collection.rs
- crates/core/src/lib.rs
- crates/core/src/link.rs
- crates/core/src/value.rs
- crates/derive/src/lib.rs
- crates/io/src/error.rs
- crates/io/src/format.rs
- crates/io/src/json.rs
- crates/io/src/lib.rs
- crates/io/src/ndjson.rs
- crates/io/src/read.rs
- crates/io/src/realized_href.rs
- crates/io/src/store.rs
- crates/pgstac/src/lib.rs
It was an abstraction we didn't need, it turns out.
> refactor!: remove `Href`
